image: maven:latest

variables:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: servicedb
  NAME: ${CI_REGISTRY_IMAGE}
  TAG: ${CI_COMMIT_SHA}

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Build project"
    - mvn package

test-job:       # This job runs in the build stage, which test application.
  stage: test
  script:
    - echo "Test project"
    - mvn test

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  image: docker:latest
  services:
    - docker:dind
  environment: production
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "Deploying application..."
    - echo "Build project"
    - docker-compose build
    - echo "Push project to registry"
    - docker push ${NAME}:${TAG}
    - echo "Delete images"
    - docker rmi ${NAME}:${TAG}
    - echo "Application successfully deployed."